


import { Inter } from 'next/font/google'
import '@ionic/react/css/core.css';

import './globals.css'




/* Basic CSS for apps built with Ionic */
import '@ionic/react/css/normalize.css';
import '@ionic/react/css/structure.css';
import '@ionic/react/css/typography.css';

/* Optional CSS utils that can be commented out */
import '@ionic/react/css/padding.css';
import '@ionic/react/css/float-elements.css';
import '@ionic/react/css/text-alignment.css';
import '@ionic/react/css/text-transformation.css';
import '@ionic/react/css/flex-utils.css';
import '@ionic/react/css/display.css';


const inter = Inter({ subsets: ['latin'] })


export const metadata = {
  title: 'App-Front',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
      <h1>Default Config body here</h1>
      <>{children}</>
 
      
      </body>
    </html>
  )
}
